name: BDD Tests (Behave)

on:
  push:
    branches: [ "main", "master", "feature*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  bdd-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave requests flask pymongo
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start Flask Server
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          nohup python app/api.py > flask_bdd_log.txt 2>&1 &
          sleep 10
          cat flask_bdd_log.txt

      - name: Run Behave Tests
        run: |
          behave